knpu_oauth2_client:
    clients:
        facebook_main:
            # this will be one of the supported types
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_facebook_check
            redirect_params: { }
            graph_api_version: v2.12
        vkontakte_main:
            # must be "vkontakte" - it activates that type!
            type: vkontakte
            # add and set these environment variables in your .env files
            client_id: '%env(OAUTH_VK_ID)%'
            client_secret: '%env(OAUTH_VK_SECRET)%'
            # a route name you'll create
            redirect_route: connect_vkontakte_check
            redirect_params: { }
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
