index:
    path: /
    controller: App\Controller\IndexController::index
view:
    path: /item/{slug}
    controller: App\Controller\IndexController:show
category-page:
    path: /category/{slug}
    controller: App\Controller\IndexController:category
create_item:
    path: /add_item
    controller: App\Controller\AddItemController:add_item
