index:
    path: /
    controller: App\Controller\IndexController::index
view:
    path: /item/{slug}
    controller: App\Controller\IndexController:show
collection-page:
    path: /collection/{slug}
    controller: App\Controller\IndexController:collection
tag-page:
    path: /tag/{slug}
    controller: App\Controller\IndexController:tag_items
create_item:
    path: /add_item/{id_collection}
    controller: App\Controller\IndexController:add_item
user_items:
    path: /user/{author}
    controller: App\Controller\IndexController:user
edit:
    path: /edit/{id}
    controller: App\Controller\IndexController:edit
remove_image:
    path: /remove_image/{id}
    controller: App\Controller\IndexController:remove_image
remove_item:
    path: /remove_item/{id}
    controller: App\Controller\IndexController:remove_item
remove_collection:
    path: /remove_collection/{id}
    controller: App\Controller\IndexController:remove_collection
create_collection:
    path: /create_collection
    controller: App\Controller\IndexController:add_collection
edit_collection:
    path: /edit_collection/{id}
    controller: App\Controller\IndexController:edit_collection
edit_gallery:
    path: /edit_gallery/{id}
    controller: App\Controller\IndexController:edit_gallery
search_form_base:
    path: /search/
    controller: App\Controller\IndexController:search_form_base
collections-page:
    path: /collections/
    controller: App\Controller\IndexController:collections
items-page:
    path: /items/
    controller: App\Controller\IndexController:items





